"""phase 5: partition ping_logs, add rollups and status pages

Hand-written rather than autogenerated: Alembic does not model declarative
partitioning, and converting an existing table means moving its data.

Revision ID: a4c71e9b02d5
Revises: d1379dfd1aa6
Create Date: 2026-09-12

"""
from datetime import date, timedelta

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "a4c71e9b02d5"
down_revision = "d1379dfd1aa6"
branch_labels = None
depends_on = None

JSONB = postgresql.JSONB(astext_type=sa.Text())

#: Months of partitions created ahead of today, matching MONTHS_AHEAD in
#: app.services.partitions. The beat task keeps this window rolling.
MONTHS_AHEAD = 3


def _month_start(when: date) -> date:
    return when.replace(day=1)


def _next_month(when: date) -> date:
    return (when.replace(day=1) + timedelta(days=32)).replace(day=1)


def _months_between(first: date, last: date) -> list[date]:
    months, cursor = [], _month_start(first)
    stop = _month_start(last)
    while cursor <= stop:
        months.append(cursor)
        cursor = _next_month(cursor)
    return months


def _partition_span(connection) -> tuple[date, date]:
    """Cover existing data plus headroom.

    Reads the real min/max so an install with a year of history gets a
    partition for every month of it, not just for today.
    """
    bounds = connection.execute(
        sa.text("SELECT min(checked_at), max(checked_at) FROM ping_logs_legacy")
    ).one()
    today = date.today()

    first = bounds[0].date() if bounds[0] else today
    last = bounds[1].date() if bounds[1] else today

    ahead = _month_start(max(last, today))
    for _ in range(MONTHS_AHEAD):
        ahead = _next_month(ahead)
    return first, ahead


def upgrade():
    connection = op.get_bind()

    # --- ping_logs -> partitioned -------------------------------------------
    #
    # The partition key must appear in every unique constraint, so the primary
    # key becomes (id, checked_at). Data is copied through a renamed table
    # rather than altered in place: a plain table cannot become a partitioned
    # one, only the parent of partitions built alongside it.
    op.execute("ALTER TABLE ping_logs RENAME TO ping_logs_legacy")
    op.execute("ALTER INDEX ix_ping_logs_monitor_checked RENAME TO ix_ping_logs_legacy_mc")
    op.execute("ALTER INDEX ix_ping_logs_org_checked RENAME TO ix_ping_logs_legacy_oc")
    op.execute("ALTER INDEX ix_ping_logs_monitor_id RENAME TO ix_ping_logs_legacy_m")
    op.execute("ALTER INDEX ix_ping_logs_org_id RENAME TO ix_ping_logs_legacy_o")

    op.execute(
        """
        CREATE TABLE ping_logs (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
            monitor_id  UUID NOT NULL REFERENCES monitors(id) ON DELETE CASCADE,
            org_id      UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            region      VARCHAR(32) NOT NULL DEFAULT 'default',
            status_code INTEGER,
            latency_ms  DOUBLE PRECISION,
            is_up       BOOLEAN NOT NULL DEFAULT false,
            error       TEXT,
            checked_at  TIMESTAMPTZ NOT NULL,
            PRIMARY KEY (id, checked_at)
        ) PARTITION BY RANGE (checked_at)
        """
    )

    first, last = _partition_span(connection)
    for month in _months_between(first, last):
        end = _next_month(month)
        op.execute(
            f'CREATE TABLE IF NOT EXISTS "ping_logs_{month.year:04d}_{month.month:02d}" '
            f"PARTITION OF ping_logs "
            f"FOR VALUES FROM ('{month.isoformat()}') TO ('{end.isoformat()}')"
        )

    # Catch-all so a probe whose timestamp falls outside every range is still
    # recorded. Losing a measurement is worse than an untidy table.
    op.execute("CREATE TABLE IF NOT EXISTS ping_logs_default PARTITION OF ping_logs DEFAULT")

    # Indexes on the parent propagate to every partition, existing and future.
    op.execute("CREATE INDEX ix_ping_logs_monitor_id ON ping_logs (monitor_id)")
    op.execute("CREATE INDEX ix_ping_logs_org_id ON ping_logs (org_id)")
    op.execute("CREATE INDEX ix_ping_logs_monitor_checked ON ping_logs (monitor_id, checked_at)")
    op.execute("CREATE INDEX ix_ping_logs_org_checked ON ping_logs (org_id, checked_at)")

    op.execute(
        """
        INSERT INTO ping_logs
            (id, monitor_id, org_id, region, status_code, latency_ms, is_up, error, checked_at)
        SELECT id, monitor_id, org_id, region, status_code, latency_ms, is_up, error, checked_at
        FROM ping_logs_legacy
        """
    )

    # Copied rows carried their own ids, so the identity sequence has to be
    # moved past them or the next insert collides.
    next_id = connection.execute(
        sa.text("SELECT coalesce(max(id), 0) + 1 FROM ping_logs")
    ).scalar()
    op.execute(f"ALTER TABLE ping_logs ALTER COLUMN id RESTART WITH {next_id}")

    op.execute("DROP TABLE ping_logs_legacy")

    # --- rollups ------------------------------------------------------------
    for table, unique_name, index_name in (
        ("ping_rollups_hourly", "uq_rollup_hourly_monitor_bucket", "ix_rollup_hourly_org_bucket"),
        ("ping_rollups_daily", "uq_rollup_daily_monitor_bucket", "ix_rollup_daily_org_bucket"),
    ):
        op.create_table(
            table,
            sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
            sa.Column("monitor_id", sa.Uuid(), nullable=False),
            sa.Column("org_id", sa.Uuid(), nullable=False),
            sa.Column("bucket", sa.DateTime(timezone=True), nullable=False),
            sa.Column("checks", sa.Integer(), nullable=False),
            sa.Column("up_checks", sa.Integer(), nullable=False),
            sa.Column("uptime_percent", sa.Float(), nullable=False),
            sa.Column("avg_latency_ms", sa.Float(), nullable=True),
            sa.Column("min_latency_ms", sa.Float(), nullable=True),
            sa.Column("max_latency_ms", sa.Float(), nullable=True),
            sa.Column("p95_latency_ms", sa.Float(), nullable=True),
            sa.Column("p99_latency_ms", sa.Float(), nullable=True),
            sa.ForeignKeyConstraint(["monitor_id"], ["monitors.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("monitor_id", "bucket", name=unique_name),
        )
        op.create_index(f"ix_{table}_monitor_id", table, ["monitor_id"])
        op.create_index(f"ix_{table}_org_id", table, ["org_id"])
        op.create_index(f"ix_{table}_bucket", table, ["bucket"])
        op.create_index(index_name, table, ["org_id", "bucket"])

    # --- status pages -------------------------------------------------------
    op.create_table(
        "status_pages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("custom_domain", sa.String(length=255), nullable=True),
        sa.Column("headline", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("support_url", sa.String(length=2048), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("history_days", sa.Integer(), nullable=False),
        sa.Column("show_urls", sa.Boolean(), nullable=False),
        sa.Column("show_latency", sa.Boolean(), nullable=False),
        sa.Column("show_incidents", sa.Boolean(), nullable=False),
        sa.Column("monitor_ids", JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "name", name="uq_status_page_org_name"),
    )
    op.create_index("ix_status_pages_org_id", "status_pages", ["org_id"])
    op.create_index("ix_status_pages_slug", "status_pages", ["slug"], unique=True)
    op.create_index(
        "ix_status_pages_custom_domain", "status_pages", ["custom_domain"], unique=True
    )


def downgrade():
    op.drop_table("status_pages")
    op.drop_table("ping_rollups_daily")
    op.drop_table("ping_rollups_hourly")

    # Collapse the partitions back into one plain table.
    op.execute("ALTER TABLE ping_logs RENAME TO ping_logs_partitioned")
    op.execute(
        """
        CREATE TABLE ping_logs (
            id          BIGSERIAL PRIMARY KEY,
            monitor_id  UUID NOT NULL REFERENCES monitors(id) ON DELETE CASCADE,
            org_id      UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            region      VARCHAR(32) NOT NULL DEFAULT 'default',
            status_code INTEGER,
            latency_ms  DOUBLE PRECISION,
            is_up       BOOLEAN NOT NULL DEFAULT false,
            error       TEXT,
            checked_at  TIMESTAMPTZ NOT NULL
        )
        """
    )
    op.execute(
        """
        INSERT INTO ping_logs
            (id, monitor_id, org_id, region, status_code, latency_ms, is_up, error, checked_at)
        SELECT id, monitor_id, org_id, region, status_code, latency_ms, is_up, error, checked_at
        FROM ping_logs_partitioned
        """
    )
    op.execute(
        "SELECT setval('ping_logs_id_seq', coalesce((SELECT max(id) FROM ping_logs), 1))"
    )
    op.execute("DROP TABLE ping_logs_partitioned CASCADE")

    op.create_index("ix_ping_logs_monitor_id", "ping_logs", ["monitor_id"])
    op.create_index("ix_ping_logs_org_id", "ping_logs", ["org_id"])
    op.create_index("ix_ping_logs_monitor_checked", "ping_logs", ["monitor_id", "checked_at"])
    op.create_index("ix_ping_logs_org_checked", "ping_logs", ["org_id", "checked_at"])
