"""phase 4: port scan scores on security_audits

Revision ID: b8666e92111c
Revises: f32a8106be15
Create Date: 2026-09-11 18:23:16.182755

"""
from alembic import op
import sqlalchemy as sa


revision = 'b8666e92111c'
down_revision = 'f32a8106be15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_audits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('port_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('port_grade', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_audits', schema=None) as batch_op:
        batch_op.drop_column('port_grade')
        batch_op.drop_column('port_score')

    # ### end Alembic commands ###
