"""phase 4: synthetic checks and runs

Revision ID: d1379dfd1aa6
Revises: b8666e92111c
Create Date: 2026-09-11 18:27:55.578198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'd1379dfd1aa6'
down_revision = 'b8666e92111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synthetic_checks',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('viewport_width', sa.Integer(), nullable=False),
    sa.Column('viewport_height', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('failure_threshold', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('interval_seconds >= 60', name='ck_synthetic_min_interval'),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_synthetic_org_name')
    )
    with op.batch_alter_table('synthetic_checks', schema=None) as batch_op:
        batch_op.create_index('ix_synthetic_checks_active_schedule', ['is_active', 'last_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_synthetic_checks_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_synthetic_checks_monitor_id'), ['monitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_synthetic_checks_org_id'), ['org_id'], unique=False)

    op.create_table('synthetic_runs',
    sa.Column('check_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'ERROR', name='run_status'), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('failed_step', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('step_results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('screenshot', sa.String(length=255), nullable=True),
    sa.Column('final_url', sa.String(length=2048), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['synthetic_checks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('synthetic_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_synthetic_runs_check_id'), ['check_id'], unique=False)
        batch_op.create_index('ix_synthetic_runs_check_started', ['check_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_synthetic_runs_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_synthetic_runs_org_started', ['org_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_synthetic_runs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('synthetic_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_synthetic_runs_status'))
        batch_op.drop_index('ix_synthetic_runs_org_started')
        batch_op.drop_index(batch_op.f('ix_synthetic_runs_org_id'))
        batch_op.drop_index('ix_synthetic_runs_check_started')
        batch_op.drop_index(batch_op.f('ix_synthetic_runs_check_id'))

    op.drop_table('synthetic_runs')
    with op.batch_alter_table('synthetic_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_synthetic_checks_org_id'))
        batch_op.drop_index(batch_op.f('ix_synthetic_checks_monitor_id'))
        batch_op.drop_index(batch_op.f('ix_synthetic_checks_is_active'))
        batch_op.drop_index('ix_synthetic_checks_active_schedule')

    op.drop_table('synthetic_checks')
    # ### end Alembic commands ###
