"""phase 2: ping_logs, ssl_scans, security_audits

Revision ID: d86aa15cdd92
Revises: 2012847b7968
Create Date: 2026-09-01 04:16:11.626853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'd86aa15cdd92'
down_revision = '2012847b7968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ping_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('is_up', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ping_logs', schema=None) as batch_op:
        batch_op.create_index('ix_ping_logs_monitor_checked', ['monitor_id', 'checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ping_logs_monitor_id'), ['monitor_id'], unique=False)
        batch_op.create_index('ix_ping_logs_org_checked', ['org_id', 'checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ping_logs_org_id'), ['org_id'], unique=False)

    op.create_table('security_audits',
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('dns_score', sa.Integer(), nullable=True),
    sa.Column('dns_grade', sa.String(length=2), nullable=True),
    sa.Column('headers_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('dns_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('open_ports', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_audits', schema=None) as batch_op:
        batch_op.create_index('ix_security_audits_monitor_created', ['monitor_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audits_monitor_id'), ['monitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audits_org_id'), ['org_id'], unique=False)

    op.create_table('ssl_scans',
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('issuer', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('days_left', sa.Integer(), nullable=True),
    sa.Column('tls_version', sa.String(length=16), nullable=True),
    sa.Column('cipher', sa.String(length=64), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('verify_error', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ssl_scans', schema=None) as batch_op:
        batch_op.create_index('ix_ssl_scans_days_left', ['days_left'], unique=False)
        batch_op.create_index('ix_ssl_scans_monitor_created', ['monitor_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ssl_scans_monitor_id'), ['monitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ssl_scans_org_id'), ['org_id'], unique=False)

    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.drop_column('last_scanned_at')
        batch_op.drop_column('last_checked_at')

    with op.batch_alter_table('ssl_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ssl_scans_org_id'))
        batch_op.drop_index(batch_op.f('ix_ssl_scans_monitor_id'))
        batch_op.drop_index('ix_ssl_scans_monitor_created')
        batch_op.drop_index('ix_ssl_scans_days_left')

    op.drop_table('ssl_scans')
    with op.batch_alter_table('security_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_audits_org_id'))
        batch_op.drop_index(batch_op.f('ix_security_audits_monitor_id'))
        batch_op.drop_index('ix_security_audits_monitor_created')

    op.drop_table('security_audits')
    with op.batch_alter_table('ping_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ping_logs_org_id'))
        batch_op.drop_index('ix_ping_logs_org_checked')
        batch_op.drop_index(batch_op.f('ix_ping_logs_monitor_id'))
        batch_op.drop_index('ix_ping_logs_monitor_checked')

    op.drop_table('ping_logs')
    # ### end Alembic commands ###
