"""phase 3: incidents, notification channels, quorum state

Revision ID: f32a8106be15
Revises: d86aa15cdd92
Create Date: 2026-09-01 04:34:25.672399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'f32a8106be15'
down_revision = 'd86aa15cdd92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_channels',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('SLACK', 'DISCORD', 'EMAIL', 'WEBHOOK', name='channel_type'), nullable=False),
    sa.Column('target', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('events', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'type', 'target', name='uq_channel_org_type_target')
    )
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.create_index('ix_notification_channels_org_active', ['org_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_channels_org_id'), ['org_id'], unique=False)

    op.create_table('incidents',
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DOWN', 'DEGRADED', 'RESOLVED', name='incident_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('regions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('notifications', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_monitor_id'), ['monitor_id'], unique=False)
        batch_op.create_index('ix_incidents_monitor_started', ['monitor_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_incidents_org_status', ['org_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)
        batch_op.create_index('uq_incidents_one_open_per_monitor', ['monitor_id'], unique=True, postgresql_where=sa.text('resolved_at IS NULL'))

    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('consecutive_degraded', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('failure_threshold', sa.Integer(), server_default='2', nullable=False))
        batch_op.add_column(sa.Column('degraded_latency_ms', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.drop_column('degraded_latency_ms')
        batch_op.drop_column('failure_threshold')
        batch_op.drop_column('consecutive_degraded')
        batch_op.drop_column('consecutive_failures')

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('uq_incidents_one_open_per_monitor', postgresql_where=sa.text('resolved_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index('ix_incidents_org_status')
        batch_op.drop_index(batch_op.f('ix_incidents_org_id'))
        batch_op.drop_index('ix_incidents_monitor_started')
        batch_op.drop_index(batch_op.f('ix_incidents_monitor_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_channels_org_id'))
        batch_op.drop_index('ix_notification_channels_org_active')

    op.drop_table('notification_channels')
    # ### end Alembic commands ###
